### ISSUE TITLE
Jobs - Explore Stateless Optimization

### ISSUE THREAD

**Issue by mbaker3** [decline-cookies/anvil-unity-dots#243]
Explore the feasibility and potential benefit of designing jobs to be stateless wherever possible. This would allow the job struct to be copied each frame rather than instantiated and re-fetching all of the required data sources (`jobData.Get...`).

### Tasks
- [ ] Measure whether all of the required data fetching is a significant impact on performance.
   - What's the performance cost vs just copying the struct?
- [ ] Explore whether our existing collections/streams could be reworked to have stateless references.
   - Are there a reasonable number of jobs that could be converted over?
- [ ] Propose a safety mechanism. 
   - Do we put attributes on all collections that support stateless job uses and assert that all references in a job have the attribute?
   - Do we decorate jobs with a stateless attribute?
   - Both?

## Initial Discussion
> Thought. Aside from thread init, most jobs are stateless after construction.
> 
> Are we wasting a bunch of time instantiating every job every frame when we could just memcopy a created one.
> I wonder what the performance impact is of skipping all of those `jobData.Get...` calls and the little stack copies, lookups, etc that happen in there.
> 
> It would be a little dangerous and you're assuming the data you require hasn't changed pointers or main thread struct values but if you design with that in mind...

> When we create the JobConfig, we probably can create the Job itself and populate it with all the references it needs to Writers/Readers.
> 
> Then during scheduling, the JobConfig would just get the right access as it does today without the need to pass the data in. If our jobs fit a certain interface that we define, we could also have it populate things that need to be done each time.
> 
> The things that won’t work (off the top of my head) are:
>  - Any of Unity’s stuff. GetEntityTypeHandle or GetCDFE etc calls, those will all have to happen at each schedule because otherwise the EntityManager state has potentially changed and we’ll get yelled at.
>     - I think we also need to do the Get to ensure we’re marking the dependencies properly.
>  - Any of Unity’s collections that don’t bundle their length.
>    - `NativeList` for example would fail because they store the Length in the struct, not on the pointer.
>    - The data would be updated the next time the job comes around, but our old copy of the job wouldn’t know because it would still have the old length and no way to change that.
> 
> Otherwise though, that could be a great optimization.

> Yea, this would purely be an optimization to reduce job prep and data fetching for the instantiation. May be that we mark jobs with attributes if we know they're compatible...or mark all the collections that support use like this and then we can have some safety enforcement
> 
> First thing though would be to measure if there even is a significant impact
